### ISSUE TITLE
Colour codes don't work

### ISSUE THREAD

**Issue by Explorer017** [DistantNetwork/PowermageCore#3]
The colour codes don't work and just display as `&c`

![image](https://user-images.githubusercontent.com/56732347/156459267-0457101b-9069-45fd-a5e6-ef7c7fb970ec.png)

**Comment by Explorer017** [comment]
This also happens in the chat, titles of menus etc.

**Comment by JakeyGilly** [comment]
fixed acidently closed wrong issue
